const fs = require('fs');
const path = require('path');

const WORDS_FILE = path.join(__dirname, '../src/data/words.json');

const newWords = [
    // root: -tract
    { id: 'word_retract', etymology_id: 'etym_tract', word: 'retract', pronunciation: 'ritrǽkt', prefix: 're-', prefix_meaning: '後ろに', root: '-tract', root_meaning_ja: '引く', suffix: '', suffix_meaning: '', combined_meaning: '後ろへ引く', meaning_ja: '撤回する', meaning_sub_ja: '引っ込める', part_of_speech: '動詞', derivatives: [{ word: 'retraction', pos: '名詞', meaning: '撤回' }], example_en: 'He retracted his statement.', example_ja: '彼は発言を撤回した。', toeic_level: 700, sort_order: 34 },
    { id: 'word_protract', etymology_id: 'etym_tract', word: 'protract', pronunciation: 'proutrǽkt', prefix: 'pro-', prefix_meaning: '前に', root: '-tract', root_meaning_ja: '引く', suffix: '', suffix_meaning: '', combined_meaning: '前に引く', meaning_ja: '長引かせる', meaning_sub_ja: '', part_of_speech: '動詞', derivatives: [], example_en: 'The meeting was protracted.', example_ja: '会議は長引いた。', toeic_level: 800, sort_order: 35 },
    { id: 'word_abstract', etymology_id: 'etym_tract', word: 'abstract', pronunciation: 'æbstrǽkt', prefix: 'abs-', prefix_meaning: '離れて', root: '-tract', root_meaning_ja: '引く', suffix: '', suffix_meaning: '', combined_meaning: '離れて引く', meaning_ja: '抽象的な', meaning_sub_ja: '要約', part_of_speech: '形容詞', derivatives: [], example_en: 'He likes abstract art.', example_ja: '彼は抽象芸術が好きだ。', toeic_level: 600, sort_order: 36 },
    { id: 'word_tractor', etymology_id: 'etym_tract', word: 'tractor', pronunciation: 'trǽktər', prefix: '', prefix_meaning: '', root: '-tract', root_meaning_ja: '引く', suffix: '-or', suffix_meaning: '〜するもの', combined_meaning: '引くもの', meaning_ja: 'トラクター', meaning_sub_ja: '牽引車', part_of_speech: '名詞', derivatives: [], example_en: 'The farmer drove a tractor.', example_ja: '農夫はトラクターを運転した。', toeic_level: 500, sort_order: 37 },
    { id: 'word_traction', etymology_id: 'etym_tract', word: 'traction', pronunciation: 'trǽkʃən', prefix: '', prefix_meaning: '', root: '-tract', root_meaning_ja: '引く', suffix: '-ion', suffix_meaning: 'こと（名詞）', combined_meaning: '引くこと', meaning_ja: '牽引', meaning_sub_ja: '推進力', part_of_speech: '名詞', derivatives: [], example_en: 'The tires lost traction on the ice.', example_ja: 'タイヤは氷上で牽引力を失った。', toeic_level: 700, sort_order: 38 },

    // root: -press
    { id: 'word_oppress', etymology_id: 'etym_press', word: 'oppress', pronunciation: 'əprés', prefix: 'ob-', prefix_meaning: '〜の方へ/逆に', root: '-press', root_meaning_ja: '押す', suffix: '', suffix_meaning: '', combined_meaning: '逆らって押す', meaning_ja: 'しいたげる', meaning_sub_ja: '圧迫する', part_of_speech: '動詞', derivatives: [{ word: 'oppression', pos: '名詞', meaning: '抑圧' }], example_en: 'The dictator oppressed the people.', example_ja: '独裁者は人々をしいたげた。', toeic_level: 800, sort_order: 31 },
    { id: 'word_repress', etymology_id: 'etym_press', word: 'repress', pronunciation: 'riprés', prefix: 're-', prefix_meaning: '後ろに', root: '-press', root_meaning_ja: '押す', suffix: '', suffix_meaning: '', combined_meaning: '後ろへ押す', meaning_ja: '抑える', meaning_sub_ja: '鎮圧する', part_of_speech: '動詞', derivatives: [{ word: 'repression', pos: '名詞', meaning: '抑圧' }], example_en: 'She repressed her anger.', example_ja: '彼女は怒りを抑えた。', toeic_level: 800, sort_order: 32 },
    { id: 'word_pressure', etymology_id: 'etym_press', word: 'pressure', pronunciation: 'préʃər', prefix: '', prefix_meaning: '', root: '-press', root_meaning_ja: '押す', suffix: '-ure', suffix_meaning: '結果・状態', combined_meaning: '押すことの結果', meaning_ja: '圧力', meaning_sub_ja: '重圧', part_of_speech: '名詞', derivatives: [], example_en: 'He works well under pressure.', example_ja: '彼はプレッシャーの下でもよく働く。', toeic_level: 500, sort_order: 33 },
    { id: 'word_press', etymology_id: 'etym_press', word: 'press', pronunciation: 'prés', prefix: '', prefix_meaning: '', root: '-press', root_meaning_ja: '押す', suffix: '', suffix_meaning: '', combined_meaning: '押す', meaning_ja: '押す', meaning_sub_ja: '報道機関', part_of_speech: '動詞', derivatives: [], example_en: 'Press the button.', example_ja: 'ボタンを押して。', toeic_level: 400, sort_order: 34 },
    { id: 'word_depression', etymology_id: 'etym_press', word: 'depression', pronunciation: 'dipréʃən', prefix: 'de-', prefix_meaning: '下に', root: '-press', root_meaning_ja: '押す', suffix: '-ion', suffix_meaning: 'こと', combined_meaning: '下に押された状態', meaning_ja: '憂鬱', meaning_sub_ja: '不況', part_of_speech: '名詞', derivatives: [], example_en: 'Economic depression affects everyone.', example_ja: '経済の不況は全ての人に影響を与える。', toeic_level: 700, sort_order: 35 },

    // root: -ject
    { id: 'word_object', etymology_id: 'etym_ject', word: 'object', pronunciation: 'άbdʒikt', prefix: 'ob-', prefix_meaning: '〜に向かって', root: '-ject', root_meaning_ja: '投げる', suffix: '', suffix_meaning: '', combined_meaning: '向かって投げられたもの', meaning_ja: '物体', meaning_sub_ja: '反対する', part_of_speech: '名詞', derivatives: [{ word: 'objection', pos: '名詞', meaning: '反対' }], example_en: 'I saw a strange object.', example_ja: '私は奇妙な物体を見た。', toeic_level: 500, sort_order: 31 },
    { id: 'word_deject', etymology_id: 'etym_ject', word: 'deject', pronunciation: 'didʒékt', prefix: 'de-', prefix_meaning: '下に', root: '-ject', root_meaning_ja: '投げる', suffix: '', suffix_meaning: '', combined_meaning: '下へ投げる', meaning_ja: '落胆させる', meaning_sub_ja: '', part_of_speech: '動詞', derivatives: [{ word: 'dejected', pos: '形容詞', meaning: '落胆した' }], example_en: 'He looked dejected.', example_ja: '彼は落胆しているようだった。', toeic_level: 800, sort_order: 32 },
    { id: 'word_trajectory', etymology_id: 'etym_ject', word: 'trajectory', pronunciation: 'trədʒéktəri', prefix: 'trans-', prefix_meaning: '横切って', root: '-ject', root_meaning_ja: '投げる', suffix: '-ory', suffix_meaning: '場所・もの', combined_meaning: '横切って投げられた道', meaning_ja: '軌道', meaning_sub_ja: '弾道', part_of_speech: '名詞', derivatives: [], example_en: 'The rocket altered its trajectory.', example_ja: 'ロケットは軌道を変えた。', toeic_level: 800, sort_order: 33 },
    { id: 'word_abject', etymology_id: 'etym_ject', word: 'abject', pronunciation: 'ǽbdʒekt', prefix: 'ab-', prefix_meaning: '離れて', root: '-ject', root_meaning_ja: '投げる', suffix: '', suffix_meaning: '', combined_meaning: '離れて投げられた', meaning_ja: '絶望的な', meaning_sub_ja: '悲惨な', part_of_speech: '形容詞', derivatives: [], example_en: 'They live in abject poverty.', example_ja: '彼らは悲惨な貧困の中で暮らしている。', toeic_level: 800, sort_order: 34 },
    { id: 'word_conjecture', etymology_id: 'etym_ject', word: 'conjecture', pronunciation: 'kəndʒéktʃər', prefix: 'con-', prefix_meaning: '共に', root: '-ject', root_meaning_ja: '投げる', suffix: '-ure', suffix_meaning: '結果', combined_meaning: '考えを共に投げ合う', meaning_ja: '推測', meaning_sub_ja: '憶測', part_of_speech: '名詞', derivatives: [], example_en: 'That is purely conjecture.', example_ja: 'それは純粋に推測にすぎない。', toeic_level: 800, sort_order: 35 },

    // root: -port
    { id: 'word_report', etymology_id: 'etym_port', word: 'report', pronunciation: 'ripɔ́ːrt', prefix: 're-', prefix_meaning: '後ろへ', root: '-port', root_meaning_ja: '運ぶ', suffix: '', suffix_meaning: '', combined_meaning: '後ろへ（情報を）持ち帰る', meaning_ja: '報告する', meaning_sub_ja: '報道', part_of_speech: '動詞', derivatives: [], example_en: 'I will report the results.', example_ja: '結果を報告します。', toeic_level: 400, sort_order: 31 },
    { id: 'word_airport', etymology_id: 'etym_port', word: 'airport', pronunciation: 'έərpɔ̀ːrt', prefix: 'air-', prefix_meaning: '空の', root: '-port', root_meaning_ja: '港', suffix: '', suffix_meaning: '', combined_meaning: '空の港', meaning_ja: '空港', meaning_sub_ja: '', part_of_speech: '名詞', derivatives: [], example_en: 'We arrived at the airport.', example_ja: '私たちは空港に到着した。', toeic_level: 300, sort_order: 32 },
    { id: 'word_passport', etymology_id: 'etym_port', word: 'passport', pronunciation: 'pǽspɔːrt', prefix: 'pass-', prefix_meaning: '通過する', root: '-port', root_meaning_ja: '港', suffix: '', suffix_meaning: '', combined_meaning: '港を通過するもの', meaning_ja: 'パスポート', meaning_sub_ja: '旅券', part_of_speech: '名詞', derivatives: [], example_en: 'Don\'t forget your passport.', example_ja: 'パスポートを忘れないで。', toeic_level: 400, sort_order: 33 },
    { id: 'word_deport', etymology_id: 'etym_port', word: 'deport', pronunciation: 'dipɔ́ːrt', prefix: 'de-', prefix_meaning: '離れて', root: '-port', root_meaning_ja: '運ぶ', suffix: '', suffix_meaning: '', combined_meaning: '運び去る', meaning_ja: '国外追放する', meaning_sub_ja: '', part_of_speech: '動詞', derivatives: [{ word: 'deportation', pos: '名詞', meaning: '国外追放' }], example_en: 'He was deported from the country.', example_ja: '彼はその国から国外追放された。', toeic_level: 800, sort_order: 34 },
    { id: 'word_portfolio', etymology_id: 'etym_port', word: 'portfolio', pronunciation: 'pɔːrtfóuliòu', prefix: 'port-', prefix_meaning: '運ぶ', root: 'folio', root_meaning_ja: '葉・紙', suffix: '', suffix_meaning: '', combined_meaning: '紙を運ぶもの', meaning_ja: '作品集', meaning_sub_ja: '紙ばさみ', part_of_speech: '名詞', derivatives: [], example_en: 'She showed me her portfolio.', example_ja: '彼女は私にポートフォリオを見せた。', toeic_level: 700, sort_order: 35 },

    // root: -mov
    { id: 'word_move', etymology_id: 'etym_mov', word: 'move', pronunciation: 'múːv', prefix: '', prefix_meaning: '', root: '-mov', root_meaning_ja: '動く', suffix: '', suffix_meaning: '', combined_meaning: '動く', meaning_ja: '動く', meaning_sub_ja: '感動させる', part_of_speech: '動詞', derivatives: [{ word: 'movement', pos: '名詞', meaning: '動き' }], example_en: 'Please move the cursor here.', example_ja: 'カーソルをここに動かしてください。', toeic_level: 400, sort_order: 1 },
    { id: 'word_remove', etymology_id: 'etym_mov', word: 'remove', pronunciation: 'rimúːv', prefix: 're-', prefix_meaning: '後ろに', root: '-mov', root_meaning_ja: '動かす', suffix: '', suffix_meaning: '', combined_meaning: '後ろに動かす', meaning_ja: '取り除く', meaning_sub_ja: '解任する', part_of_speech: '動詞', derivatives: [{ word: 'removal', pos: '名詞', meaning: '除去' }], example_en: 'Remove the dirt from your shoes.', example_ja: '靴の汚れを取り除いて。', toeic_level: 500, sort_order: 2 },
    { id: 'word_promote', etymology_id: 'etym_mov', word: 'promote', pronunciation: 'prəmóut', prefix: 'pro-', prefix_meaning: '前に', root: '-mot', root_meaning_ja: '動かす', suffix: '', suffix_meaning: '', combined_meaning: '前に動かす', meaning_ja: '促進する', meaning_sub_ja: '昇進させる', part_of_speech: '動詞', derivatives: [{ word: 'promotion', pos: '名詞', meaning: '昇進・促進' }], example_en: 'He was promoted to manager.', example_ja: '彼は部長に昇進した。', toeic_level: 600, sort_order: 3 },
    { id: 'word_remote', etymology_id: 'etym_mov', word: 'remote', pronunciation: 'rimóut', prefix: 're-', prefix_meaning: '後ろに', root: '-mot', root_meaning_ja: '動かされた', suffix: '', suffix_meaning: '', combined_meaning: '後ろに遠ざけられた', meaning_ja: '遠い', meaning_sub_ja: 'リモートの', part_of_speech: '形容詞', derivatives: [], example_en: 'They live in a remote village.', example_ja: '彼らは遠く離れた村に住んでいる。', toeic_level: 500, sort_order: 4 },
    { id: 'word_motion', etymology_id: 'etym_mov', word: 'motion', pronunciation: 'móuʃən', prefix: '', prefix_meaning: '', root: '-mot', root_meaning_ja: '動く', suffix: '-ion', suffix_meaning: 'こと', combined_meaning: '動くこと', meaning_ja: '動き', meaning_sub_ja: '動議', part_of_speech: '名詞', derivatives: [], example_en: 'She made a hand motion.', example_ja: '彼女は手で合図（動き）をした。', toeic_level: 500, sort_order: 5 },
    { id: 'word_motive', etymology_id: 'etym_mov', word: 'motive', pronunciation: 'móutiv', prefix: '', prefix_meaning: '', root: '-mot', root_meaning_ja: '動かす', suffix: '-ive', suffix_meaning: '性質', combined_meaning: '動かす性質を持つもの', meaning_ja: '動機', meaning_sub_ja: '目的', part_of_speech: '名詞', derivatives: [], example_en: 'What was his motive for the crime?', example_ja: '犯罪の動機は何でしたか？', toeic_level: 600, sort_order: 6 },
    { id: 'word_emotion', etymology_id: 'etym_mov', word: 'emotion', pronunciation: 'imóuʃən', prefix: 'e-', prefix_meaning: '外に', root: '-mot', root_meaning_ja: '動く', suffix: '-ion', suffix_meaning: 'こと', combined_meaning: '外に動き出すもの', meaning_ja: '感情', meaning_sub_ja: '感動', part_of_speech: '名詞', derivatives: [{ word: 'emotional', pos: '形容詞', meaning: '感情的な' }], example_en: 'He hid his emotion.', example_ja: '彼は感情を隠した。', toeic_level: 500, sort_order: 7 },
    { id: 'word_motor', etymology_id: 'etym_mov', word: 'motor', pronunciation: 'móutər', prefix: '', prefix_meaning: '', root: '-mot', root_meaning_ja: '動かす', suffix: '-or', suffix_meaning: 'もの', combined_meaning: '動かすもの', meaning_ja: 'モーター', meaning_sub_ja: '原動機', part_of_speech: '名詞', derivatives: [], example_en: 'The motor stopped working.', example_ja: 'モーターが動かなくなった。', toeic_level: 400, sort_order: 8 },
    { id: 'word_motivate', etymology_id: 'etym_mov', word: 'motivate', pronunciation: 'móutəvèit', prefix: '', prefix_meaning: '', root: '-mot', root_meaning_ja: '動かす', suffix: '-ate', suffix_meaning: 'させる', combined_meaning: '動かすようにさせる', meaning_ja: '動機づける', meaning_sub_ja: 'やる気を出させる', part_of_speech: '動詞', derivatives: [{ word: 'motivation', pos: '名詞', meaning: 'やる気' }], example_en: 'A good teacher motivates students.', example_ja: '良い教師は生徒を動機づける。', toeic_level: 700, sort_order: 9 },
    { id: 'word_demote', etymology_id: 'etym_mov', word: 'demote', pronunciation: 'dimóut', prefix: 'de-', prefix_meaning: '下に', root: '-mot', root_meaning_ja: '動かす', suffix: '', suffix_meaning: '', combined_meaning: '下に動かす', meaning_ja: '降格させる', meaning_sub_ja: '', part_of_speech: '動詞', derivatives: [{ word: 'demotion', pos: '名詞', meaning: '降格' }], example_en: 'He was demoted for poor performance.', example_ja: '彼は業績不良で降格させられた。', toeic_level: 800, sort_order: 10 },
    { id: 'word_mobile', etymology_id: 'etym_mov', word: 'mobile', pronunciation: 'móubəl', prefix: '', prefix_meaning: '', root: '-mov', root_meaning_ja: '動く', suffix: '-ible', suffix_meaning: 'できる', combined_meaning: '動くことができる', meaning_ja: '移動できる', meaning_sub_ja: '携帯の', part_of_speech: '形容詞', derivatives: [{ word: 'mobility', pos: '名詞', meaning: '流動性' }], example_en: 'Mobile phones are ubiquitous.', example_ja: '携帯電話はどこにでもある。', toeic_level: 400, sort_order: 11 },
];

function expand() {
    try {
        const data = fs.readFileSync(WORDS_FILE, 'utf8');
        let words = JSON.parse(data);

        let addedCount = 0;
        newWords.forEach(nw => {
            // Avoid duplication
            if (!words.find(w => w.word === nw.word)) {
                words.push(nw);
                addedCount++;
            }
        });

        fs.writeFileSync(WORDS_FILE, JSON.stringify(words, null, 2), 'utf8');
        console.log(`Successfully added ${addedCount} words to the database.`);
    } catch (e) {
        console.error('Error expanding words:', e);
    }
}

expand();
